miniaturesregistrar/miniaturesregistrar/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from minis.views import AddMiniView, MiniColorsView, ElementView, MainView, \
    RegisterView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'logout/$', logout_then_login, name="site-logout"),
    url(r'^add_mini/$', AddMiniView.as_view(), name='add-mini'),
    url(r'^minicolors/(?P<miniature_id>\d+)/?$', MiniColorsView.as_view(),
        name="mini-colors"),
    url(r'^element_view/(?P<id>(\d)+)$', ElementView.as_view(),
        name="element"),
    url(r'^$', MainView.as_view(), name="main"),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^register/$', RegisterView.as_view(), name="register"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miniaturesregistrar/minis/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

MINIATURE_ELEMENTS = (
    (0, "Skin"),
    (1, "Weapon_wood"),
    (2, "Eyes"),
    (3, "Armor"),
    (4, "Weapon_steel"),
    (5, "Clothes_upper"),
    (6, "Clothes_lower"),
    (7, "Boots"),
    (8, "Golden_elements"),
    (9, "Bone_elements"),
    (10, "Base")
)


class System(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Army(models.Model):
    system = models.ForeignKey(System)
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Paint(models.Model):
    name = models.CharField(max_length=64)
    manufacturer = models.ForeignKey("PaintManufacturer")

    def __str__(self):
        return self.name


class Miniature(models.Model):
    army = models.ForeignKey(Army)
    name = models.CharField(max_length=128)
    mini_image = models.ImageField(null=True, blank=True)
    paint = models.ManyToManyField(Paint)
    comment = models.TextField(blank=True)
    user = models.ForeignKey(User, null=True)

    def __str__(self):
        return self.name


class PaintManufacturer(models.Model):
    manufacturer = models.CharField(max_length=64)

    def __str__(self):
        return self.manufacturer


class Element(models.Model):
    paints = models.ManyToManyField(Paint)
    miniature = models.ForeignKey(Miniature, related_name='elements')
    number = models.IntegerField(choices=MINIATURE_ELEMENTS)

miniaturesregistrar/miniaturesregistrar/forms.py
from django import forms
from minis.models import Army, System, Miniatures, PaintManufacturer, Colors


class AddMini(forms.Form):
    army_choice = forms.ModelChoiceField(queryset=Army.objects.all(),
                                         required=True, empty_label="----",)
    system_choice = forms.ModelChoiceField(queryset=System.objects.all(),
                                           required=True, empty_label="----")
    miniature_choice = forms.ModelChoiceField(
                                            queryset=Miniatures.objects.all(),
                                            required=True, empty_label="----")

miniaturesregistrar/minis/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from minis.models import Army, System


class AddMiniForm(forms.Form):
    system = forms.ModelChoiceField(queryset=System.objects.all(),
                                    required=True, empty_label="----")
    army = forms.ModelChoiceField(queryset=Army.objects.all(),
                                  required=True, empty_label="----",)
    name = forms.CharField(max_length=128, required=True)
    image = forms.ImageField(required=False)


def validate_username(value):
    if User.objects.filter(username=value).exists():
        raise ValidationError('Username already exists!')


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=16, required=True,
                               validators=[validate_username])
    email = forms.EmailField(required=True)
    password = forms.CharField(max_length=128, required=True,
                               widget=forms.PasswordInput)

miniaturesregistrar/minis/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect, Http404
from django.views import View
from django.views.generic import FormView
from minis.forms import AddMiniForm, RegistrationForm
from minis.models import Miniature, Paint, PaintManufacturer, MINIATURE_ELEMENTS, Element, System
from rest_framework.response import Response
from rest_framework.views import APIView
import json


# Create your views here.


class AddMiniView(LoginRequiredMixin, FormView):
    template_name = 'minis/addmini_form.html'
    form_class = AddMiniForm

    def form_valid(self, form):
        army = form.cleaned_data['army']
        name = form.cleaned_data['name']
        user = self.request.user
        if 'image' in self.request.FILES:
            image = self.request.FILES['image']
        else:
            image = None
        miniature = Miniature.objects.create(army=army, name=name,
                                             user=user, mini_image=image)
        return redirect("mini-colors", miniature.id)


class MiniColorsView(LoginRequiredMixin, View):
    def get(self, request, miniature_id):
        miniature = get_object_or_404(Miniature, pk=miniature_id,
                                      user=request.user)
        manufacturers = PaintManufacturer.objects.all()
        element_types = MINIATURE_ELEMENTS
        elements = Miniature.objects.get(pk=miniature_id).elements

        # list of [el_type_id, el_type_name, paints]
        el_types = []
        for el_type_id, el_type_name in element_types:
            elements_of_this_type = elements.filter(number=el_type_id)

            if elements_of_this_type.count() > 0:
                element = elements_of_this_type[0]
                all_paints = element.paints.all()

                paints = [
                    all_paints[0] if all_paints.count() > 0 else None,
                    all_paints[1] if all_paints.count() > 1 else None,
                    all_paints[2] if all_paints.count() > 2 else None,
                ]
            else:
                paints = [None, None, None]

            el_types.append([el_type_id, el_type_name, paints])

        for m in manufacturers:
            m.paints = m.paint_set.all()

        return render(request, 'minis/mini_colors.html', {
            'miniature': miniature,
            'manufacturers': manufacturers,
            'elements': element_types,
            'el_type': el_types,
            'paint_range': range(3),
        })


class ElementView(LoginRequiredMixin, APIView):
    def post(self, request, id, format=None):
        miniature = get_object_or_404(Miniature, pk=id, user=request.user)

        comment = request.data['comment']
        all_colors = request.data['colors']
        for index, colors in enumerate(json.loads(all_colors)):
            print(index, colors)
            element, _create = Element.objects.get_or_create(
                number=index, miniature=miniature)
            for paint_pk in map(int, filter(lambda x: x, colors)):
                element.paints.add(Paint.objects.get(pk=paint_pk))
            element.save()

        miniature.comment = comment
        miniature.save()

        return Response('OK')


class MainView(LoginRequiredMixin, View):
    def get(self, request):
        user_miniatures = Miniature.objects.filter(user=request.user)

        systems = System.objects.all()
        return render(request, 'minis/main_page.html', {
            'systems': systems,
            'user_miniatures': user_miniatures,
        })


class RegisterView(FormView):
    template_name = 'registration/registration_form.html'
    form_class = RegistrationForm

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        User.objects.create_user(username, email, password)
        return redirect('main')

miniaturesregistrar/minis/templates/minis/addmini_form.html
{% extends 'minis/base.html' %}
{% block title %}
Add your mini!
{% endblock %}

{% block content %}
    <div class="panel panel-success">
        <div class="panel-heading">
            Miniatures
        </div>
        <div class="panel-body">

                    <p><b>Add mini:</b></p>
            <div>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Forward">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

miniaturesregistrar/minis/templates/minis/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add miniature</title>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery=1 %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}" >
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>


    <div class="topmenu">
        <p class="navbar-right logout">
            Signed in as: {{ request.user.username }}
            <a class="menuspace" href="{% url 'main' %}">Home</a>
            <a class="menuspace" href="{% url 'site-logout' %}?next=/">LOGOUT</a>
        </p>
    </div>
    <div class="base-headline-title">
        <h3>
            {% block title %}{% endblock %}
        </h3>
    </div>

    <div class="content-block">
        {% block content %}
        {% endblock %}
    </div>

    {% bootstrap_javascript %}
    <script type="text/javascript" src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    {% block content_js %}
    {% endblock %}
</body>
</html>

miniaturesregistrar/minis/templates/minis/main_page.html
{% extends 'minis/base.html' %}

{% block title %}
    Your awesome miniatures
{% endblock %}

{% block content %}
    {% for system in systems %}
        <div class="panel panel-default">
            <div class="panel-heading"><strong>{{ system.name }}</strong></div>
            <div class="panel-body">
                <ul>
                {% for army in system.army_set.all %}
                    <li><strong>{{ army.name }}</strong>
                        <ul>
                        {% for miniature in army.miniature_set.all %}
                            {% if miniature in user_miniatures %}
                            <li>
                                <a href="{% url 'mini-colors' miniature.id %}">{{ miniature.name }}</a>
                            </li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}
    <a class='btn btn-primary' href="{% url 'add-mini' %}">Add mini!</a>
{% endblock %}

miniaturesregistrar/minis/templates/minis/mini_colors.html
{% extends 'minis/base.html' %}
{% load static %}

{% block title %}
    Your colors!
{% endblock %}
{% block content %}
    {% csrf_token %}
    <input type="hidden" id="miniature-id" value="{{ miniature.id }}">
    <input type="hidden" id="element-view-url" value="{% url 'element' miniature.id %}">
    <div class="panel panel-success">
        <div class="panel-heading">
            Colors for <strong>{{ miniature.name }}</strong>
        </div>
        <div class="panel-body">
            System: <strong>{{ miniature.army.system.name }}</strong> <br>
            Army: <strong>{{ miniature.army.name }}</strong> <br>
            {% if miniature.mini_image %}
                Image: <img src='{{ miniature.mini_image.url }}'>
            {% endif %}
        </div>
    </div>
    <ul class="list-group">
        {% for id, name, paints in el_type %}
            <li class="list-group-item">{{ name }}
            <br>
            {% for paint in paints %}
                <select>
                    <option value=""></option>
                    {% for p_m in manufacturers %}
                        <option disabled>{{ p_m.manufacturer }}</option>
                        {% for p in p_m.paints %}
                            <option value="{{ p.id }}" {% if p.id == paint.id %}selected{% endif %}>{{ p.name }}</option>
                        {% endfor %}
                    {% endfor %}
                </select>
            {% endfor %}
            </li>
        {% endfor %}
    </ul>

    <textarea id="comment">{{ miniature.comment }}</textarea>

<button id="save">Save</button>
<div id="save-message"></div>
<script type="text/javascript" src="{% static 'bnt.js' %}"></script>
</div>
{% endblock %}